//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectModels.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lawyer
    {
        public Lawyer()
        {
            this.Clients = new HashSet<Client>();
        }
    
        public int Id { get; set; }
        public int CompanyId { get; set; }
        public string Name { get; set; }
        public int LawyerTypeId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public string Status { get; set; }
    
        public virtual ICollection<Client> Clients { get; set; }
        public virtual Company Company { get; set; }
        public virtual LawyerType LawyerType { get; set; }
    }
}
